getting ready for merge

diff --git a/mythic-docker/Dockerfile b/mythic-docker/Dockerfile
--- a/mythic-docker/Dockerfile
+++ b/mythic-docker/Dockerfile
@@ -1,26 +1,26 @@
-#FROM ghcr.io/its-a-feature/mythic_server:v0.0.2.32
+FROM ghcr.io/its-a-feature/mythic_server:v0.0.2.32
 
-FROM itsafeaturemythic/mythic_go_base:latest
+#FROM itsafeaturemythic/mythic_go_base:latest
 
-WORKDIR /usr/src/app
+#WORKDIR /usr/src/app
 
-ARG GOPROXY=proxy.golang.org
-ARG GO111MODULE
+#ARG GOPROXY=proxy.golang.org
+#ARG GO111MODULE
 
-RUN go env -w GOPROXY=${GOPROXY}
-RUN go env -w GO111MODULE=${GO111MODULE}
+#RUN go env -w GOPROXY=${GOPROXY}
+#RUN go env -w GO111MODULE=${GO111MODULE}
 
-COPY ["src/", "."]
+#COPY ["src/", "."]
 
-RUN make build_final
+#RUN make build_final
 
-FROM alpine
+#FROM alpine
 
-COPY --from=0 /mythic_server /mythic_server
+#COPY --from=0 /mythic_server /mythic_server
 
-WORKDIR /usr/src/app
+#WORKDIR /usr/src/app
 
-HEALTHCHECK --interval=60s --timeout=10s --retries=5 --start-period=20s \
-  CMD wget -SqO - http://127.0.0.1:${MYTHIC_SERVER_PORT:-17443}/health || exit 1
+#HEALTHCHECK --interval=60s --timeout=10s --retries=5 --start-period=20s \
+#  CMD wget -SqO - http://127.0.0.1:${MYTHIC_SERVER_PORT:-17443}/health || exit 1
 
-CMD ["/bin/sh", "-c", "cp /mythic_server . && ./mythic_server" ]
+#CMD ["/bin/sh", "-c", "cp /mythic_server . && ./mythic_server" ]
